# action.yml
name: 'Scala SBT Action'
author: 'Matan Keidar <matankdr@gmail.com>'
description: 'SBT build tool action with docker'
inputs:
  command:  # id of input
    description: 'Commands to run'
    required: true
  packages-resolver:  # packages resolver
    description: 'packages resolver'
    required: true
  docker-login-username:  # Docker login username
    description: 'docker login username'
    required: false
  docker-login-password:  # Docker login password
    description: 'docker login password'
    required: false
  docker-registry:  # Docker registry
    description: 'docker registry'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.packages-resolver }}
    - ${{ inputs.docker-login-username }}
    - ${{ inputs.docker-login-password }}
    - ${{ inputs.docker-registry }}

branding:
  icon: 'package'
  color: 'blue'
